version: "3.9"

services:
  django_app:
    build: .
    ports:
      - "8001:8001"  # Django acessível no host pela porta 8001
    volumes:
      - ./backend:/backend
    working_dir: /backend
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
      POSTGRES_DB: meudb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    command: ["./wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8001"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: meudb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d meudb"]
      interval: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
